### ISSUE TITLE
Retry on only server side error

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-csi/external-provisioner#153]
/kind feature

[external-provisioner controller](https://github.com/kubernetes-csi/external-provisioner/blob/master/pkg/controller/controller.go#L463-L475) should only retry on server side error (including timeout). Retrying on client side error is not very useful and the error could be simply returned immediately in favor of fail fast.

**Comment by pohly** [comment]
@leakingtapan what do you mean with "client" and "server" side here? "client" = external-provisioner, "server" = CSI driver? If `Provision` returns an error, is there another retry loop higher up in the stack that'll call it again, or is that error then permanent?

**Comment by pohly** [comment]
Looks like you answered that already in #154: once `Provision` returns an error, there's no next retry attempt.

My personal expectation is that as long as a PVC exists, provisioning gets retried in perpetuity with increasing backoff. Looks like that retry loop is (has to be?) in external-provisioner.

One could try to detect "permanent" errors, but what is "permanent"? Even a config error for the CSI driver might go away once an admin fixes the config, and then the next provisioning attempt can succeed.

**Comment by verult** [comment]
To clarify - the provisioner will retry `Provision` on error until a retry threshold (by default it's 15) is met

**Comment by leakingtapan** [comment]
@pohly yep. By client side I mean external-provisioner and server side is CSI driver. Here is one specific example I experienced that should not be retried:

I created a storageclass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: voltype-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: com.amazon.aws.csi.ebs
parameters:
  type: io1
  iopsPerGB: "100"
```
Where `iopsPerGB` is only allowed to be 50 max. In this case, volume creation will fail because `iopsPerGB` is too high. However, provisioner will keep trying with the same value. For a user who creates PV/PVC, if the error could be surfaced early, he will be able to fix the error right away instead of wondering why PV/PVC is keep being pending.
