### ISSUE TITLE
Use csi.driver in PV spec for volume deletion

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-csi/external-provisioner#202]
/feature

Currently, if I want CSI PV to be deleted with reclaim policy set to Delete, I need to set provisioner annotation on the PV manifest as follows:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-test2
  annotations:
    pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext3
    volumeHandle: vol-05cee971d935278ac
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
```
This is not well documented and is confusing for user who provisions CSI PV manually. Since provisioner name (driver name) is already available in CSI Volume of PV spec, external provisioner should be able to reuse this information instead of relying on annotation

/cc @msau42
