### ISSUE TITLE
CreateVolume is not triggered by provisioner

### ISSUE THREAD

**Issue by kaleo211** [kubernetes-csi/external-provisioner#443]
Hi,

I try to deploy my driver alone with provisioner. the whole deployment got running without error. While I was trying to create a new PersistentVolume, the CreateVolume was not invoked. And here is the log for provisioner:
```
1 feature_gate.go:243] feature gates: &{map[]}
1 csi-provisioner.go:107] Version: v1.6.0-0-g321fa5c1c
1 csi-provisioner.go:121] Building kube configs for running in cluster...
1 round_trippers.go:443] GET https://10.96.0.1:443/version?timeout=32s 200 OK in 8 milliseconds
1 connection.go:153] Connecting to unix:///plugin/csi.sock
1 common.go:111] Probing CSI driver for readiness
1 connection.go:182] GRPC call: /csi.v1.Identity/Probe
1 connection.go:183] GRPC request: {}
1 connection.go:185] GRPC response: {}
1 connection.go:186] GRPC error: <nil>
1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginInfo
1 connection.go:183] GRPC request: {}
1 connection.go:185] GRPC response: {"name":"sdnas.csi.k8s.io","vendor_version":"2020.5.0"}
1 connection.go:186] GRPC error: <nil>
1 csi-provisioner.go:163] Detected CSI driver sdnas.csi.k8s.io
1 metrics.go:142] metrics endpoint will not be started because `metrics-address` was not specified.
1 connection.go:182] GRPC call: /csi.v1.Identity/GetPluginCapabilities
1 connection.go:183] GRPC request: {}
1 connection.go:185] GRPC response: {"capabilities":[{"Type":{"Service":{"type":1}}}]}
1 connection.go:186] GRPC error: <nil>
1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
1 connection.go:183] GRPC request: {}
1 connection.go:185] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}}]}
1 connection.go:186] GRPC error: <nil>
1 controller.go:709] Using saving PVs to API server in background

1 reflector.go:153] Starting reflector *v1.StorageClass (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/v5/controller/controller.go:836
1 reflector.go:188] Listing and watching *v1.StorageClass from sigs.k8s.io/sig-storage-lib-external-provisioner/v5/controller/controller.go:836
1 reflector.go:153] Starting reflector *v1.PersistentVolumeClaim (15m0s) from github.com/kubernetes-csi/external-provisioner/pkg/controller/clone_controller.go:72
1 reflector.go:188] Listing and watching *v1.PersistentVolumeClaim from github.com/kubernetes-csi/external-provisioner/pkg/controller/clone_controller.go:72
1 reflector.go:153] Starting reflector *v1.PersistentVolume (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/v5/controller/controller.go:833
1 reflector.go:188] Listing and watching *v1.PersistentVolume from sigs.k8s.io/sig-storage-lib-external-provisioner/v5/controller/controller.go:833

1 reflector.go:432] github.com/kubernetes-csi/external-provisioner/pkg/controller/clone_controller.go:72: Watch close - *v1.PersistentVolumeClaim total 2 items received
1 reflector.go:432] sigs.k8s.io/sig-storage-lib-external-provisioner/v5/controller/controller.go:836: Watch close - *v1.StorageClass total 2 items received
1 reflector.go:432] k8s.io/client-go/informers/factory.go:135: Watch close - *v1.StorageClass total 2 items received
1 reflector.go:432] sigs.k8s.io/sig-storage-lib-external-provisioner/v5/controller/controller.go:833: Watch close - *v1.PersistentVolume total 3 items received
```

deployment.yml
```
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: csi-sdnas-controller
spec:
  selector:
    matchLabels:
      app: csi-sdnas-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-sdnas-controller
    spec:
      serviceAccount: csi-plugin
      hostNetwork: true
      containers:
      - name: external-provisioner
        image: quay.io/k8scsi/csi-provisioner:v1.6.0
        args:
        - --csi-address=/plugin/csi.sock
        - --v=6
        volumeMounts:
        - name: plugin-dir
          mountPath: /plugin
      - name: controller
        image: kaleo211/csi-driver-sdnas
        imagePullPolicy: Always
        args:
        - "--mode=$(MODE)"
        - "--endpoint=$(CSI_ENDPOINT)"
        env:
        - name: MODE
          value: controller
        - name: CSI_ENDPOINT
          value: unix:///plugin/csi.sock
        volumeMounts:
        - name: plugin-dir
          mountPath: /plugin
      volumes:
      - name: plugin-dir
        emptyDir: {}
```

the PersistentVolume.yml
```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sdnas-sc
provisioner: sdnas.csi.k8s.io
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sdnas
  labels:
    name: sdnas
spec:
  storageClassName: sdnas-sc
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 100Gi
  csi:
    driver: sdnas.csi.k8s.io
    volumeHandle: sdnas

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdnas
spec:
  storageClassName: sdnas-sc
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
  selector:
    matchExpressions:
    - key: name
      operator: In
      values: ["sdnas"]
```

Hope someone can give me some help!

**Comment by RaunakShah** [comment]
Hi @kaleo211 if you're hoping to invoke callbacks on your CSI driver, you'll need to dynamically provision this volume by only creating the PersistentVolumeClaim (PVC). If volume provisioning succeeds, then a PersistentVolume (PV) will be created and bound to this PVC. 
Also, i see that you storage class has `volumeBindingMode` set to `WaitForFirstConsumer`, which means that this volume (and PV) will not be created until you create a Pod that claims this volumes. 
Can you replace your YAMLs above with the following and give it a shot: 

```
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sdnas-sc
provisioner: sdnas.csi.k8s.io
reclaimPolicy: Delete
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdnas
spec:
  storageClassName: sdnas-sc
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
```

Hope this helps!
