### ISSUE TITLE
Pass namespace annotations to driver when --extra-create-metadata is enabled

### ISSUE THREAD

**Issue by rdpsin** [kubernetes-csi/external-provisioner#714]
Currently, `external-provisioner` passes the PVC name, PVC namespace and PV name to the CSI driver in `CreateVolumeRequest.Parameters`, when `extra-create-metadata` is enabled. 

It would be useful to also pass namespace annotations to the CSI driver as well. This can be very helpful to cluster admins since a common design is to set boundaries/controls at the namespace level. For e.g., this can allow the CSI driver to attach namespace annotations as tags to the volume for cost allocation, backups, IAM policies, et cetera. 

Design:

A new parameter is created: `csi.storage.k8s.io/pvc/namespace/annotations` where the value is a string of comma separated key-value pairs.

```
csi.storage.k8s.io/pvc/namespace/annotations: "foo=bar,baz=test"
```

Note that similar proposals have been put forward, but they include passing PVC annotations to the CSI driver (see #86).

**Comment by rdpsin** [comment]
cc: @xing-yang

**Comment by paolosalvatori** [comment]
I fully support this request. Today you cannot specify metadata and, in particular, tags in a PVC that are passed down to a CSI driver. Tagging resources is helpful in a multitenant environment for policy tracking and cost charging. Today, the only way to tag managed resources dynamically created by a PVC on a cloud platform is the following:

- Create a custom storage class and specify tags in the parameters:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: contoso-managed-csi-premium
provisioner: disk.csi.azure.com
parameters:
  skuname: Premium_LRS
  tags: costcenter=1234,tenant=Contoso
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```
- Create a PVC based on the custom storage class:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: contoso-managed-csi-premium
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: contoso-managed-csi-premium
  resources:
    requests:
      storage: 50Gi
```
- Use the PVC in your deployment definition

In a multi-tenant environment, this approach can lead to two kinds of problems:

- Proliferation of custom storage classes, one for each tenant. If you share an AKS cluster across hundreds of tenants each using PVs, and you want to use this technique to tag managed disks, you can quickly end up with hundreds of custom storage classes
- Storage classes are not namespaced resources, so this can lead to issues when trying to segregate or restrict security using Kubernetes RBAC or Azure AD integrated RBAC

You can use a trick to avoid the proliferation of storage classes: 

- You can create a custom storage class with the proper tags for a tenant
- Based on the custom storage class, create one or more PVCs, which dynamically create related managed resources on the current cloud platform. 
- Delete the custom storage class.

This solution is doable, but it's not very clean.
