### ISSUE TITLE
[provisioner-env-configuration] Fix example environment variables configuration 

### ISSUE THREAD

**Issue by gregth** [kubernetes-csi/external-provisioner#721]
The example configuration for the environment variables in the documentation / README file has some typos:

```yaml
   env:
   - name: NAMESPACE
     valueFrom:
        fieldRef:
        fieldPath: metadata.namespace
   - name: POD_NAME
     valueFrom:
        fieldRef:
        fieldPath: metadata.name
```

The `fieldPath` should be indented under the `fieldRef`:

```diff
    env:
    - name: NAMESPACE
      valueFrom:
-        fieldRef:
-        fieldPath: metadata.namespace
+       fieldRef:
+         fieldPath: metadata.namespace
    - name: POD_NAME
      valueFrom:
-        fieldRef:
-        fieldPath: metadata.name
+       fieldRef:
+         fieldPath: metadata.name
```
